### ISSUE TITLE
Criar Estrutura de classes MarcasModeloCompativeis para gerar arquivo em XML

### ISSUE THREAD

**Issue by koziel101** [isaiastavares/XMLGenerator#39]
Estrutura do XML a ser gerado:
 
< MarcasModelosCompativeis> 116
 < MarcaModelo> 117
 < Marca>Marca</ Marca> 118
 < Modelo>Modelo</ Modelo> 119
 </ MarcaModelo>
 </ MarcasModelosCompativeis>

**Comment by LeonardoKalyn** [comment]
Como a classe MarcaModelo já existe, essa classe está englobada na na issue Refatoração das Classes com Listas de Elementos.

**Comment by matcheus** [comment]
@LeonardoKalyn você já fez essa classe então? Porque reabriu a Issue?

**Comment by LeonardoKalyn** [comment]
Tinha reaberto por causa de uma das refatorações que englobava ela. mas ja esta resolvido
