### ISSUE TITLE
Criar Estrutura de classes ComentarioOtc para gerar arquivo em XML

### ISSUE THREAD

**Issue by koziel101** [isaiastavares/XMLGenerator#42]
Estrutura do XML a ser gerado:

< ComentarioOtc></ ComentarioOtc> 130
< Emissao> 131
 < Data>2013-09-16</ Data> 132
 < Local></ Local> 133
 </ Emissao>
 < ExecucaoTestes> 134
 < Nome>Nome</ Nome> 135
 < Cargo>Cargo</ Cargo> 136
 < Cpf>11111111111</ Cpf> 137
 </ ExecucaoTestes>

**Comment by MarjorieCelestino** [comment]
As classes Emissao e Execução já foram criadas e a String ComentarioOtc também foi criada na classe Mensagem.
